---
name: Arduino_lint # https://github.com/marketplace/actions/arduino-arduino-lint-action

on: [push, pull_request]

jobs:
  Arduino_Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
        with:
          path: ./src/main/
          project-type: all # (sketch, library, platform, package-index, all)
          library-manager: update
          compliance: specification  #strict
          verbose: true
