name: ShellCheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install ShellCheck
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      # Step 3: Run ShellCheck on all shell scripts
      - name: Run ShellCheck
        run: |
          # Find and lint all shell scripts (*.sh)
          find . -type f -name "*.sh" -exec shellcheck {} +
